default_settings: null
behaviors:
  ZombieWalker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      learning_rate_schedule: linear
      num_epoch: 3
      num_layers: 2
      hidden_units: 128
      normalize: true
    network_settings:
      normalize: true
      hidden_units: 128
    max_steps: 100000

    # Additional Parameters
    num_parallel_envs: 12
    gamma: 0.99
    time_horizon: 2048
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    vis_encode_type: custom
    normalize: false
    memory_size: 256
    curiosity_strength: 0.0
    curiosity_enc_size: 1
    curiosity_time_horizon: 64